name = "jiwonz/pathfs"
version = "0.3.1"
description = "luau-path + @lune/fs"
license = "MIT"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/lune-path-fs/"
private = false
includes = ["README.md", "pesde.toml", "src/**", "LICENSE.md"]

[target]
environment = "lune"
lib = "src/lib/init.luau"

[dependencies.greentea]
name = "corecii/greentea"
version = "^0.4.11"
index = "https://github.com/daimond113/pesde-index"

[dependencies.luau_path]
name = "jiwonz/luau_path"
version = "^0.1.1"
index = "https://github.com/daimond113/pesde-index"
target = "luau"

[dev_dependencies.frktest]
name = "itsfrank/frktest"
version = "^0.0.2"
index = "https://github.com/daimond113/pesde-index"

[dev_dependencies.luau_lsp]
name = "pesde/luau_lsp"
version = "^1.38.1"
index = "https://github.com/daimond113/pesde-index"

[dev_dependencies.selene]
name = "pesde/selene"
version = "^0.27.1"
index = "https://github.com/daimond113/pesde-index"

[dev_dependencies.stylua]
name = "pesde/stylua"
version = "^2.0.2"
index = "https://github.com/daimond113/pesde-index"
