name = "jiwonz/luau_path"
version = "0.1.1"
description = "A Luau library to handle file paths based on the Rust path library by jeparlefrancais, Uploaded for pesde"
license = "MIT"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>"]
repository = "https://github.com/seaofvoices/luau-path"
private = false
includes = ["src", "README.md", "LICENSE.txt", "pesde.toml"]

[target]
environment = "luau"
lib = "src/init.luau"

[dependencies.luau_disk]
name = "jiwonz/luau_disk"
version = "^0.1.2"
index = "https://github.com/pesde-pkg/index"
